# You want to model the volatility of the stock. You assume that, for all periods
# t = 1, . . . , T, the stock return rt are generated by a location scale model

# Follows 2021 reexam
# When we use a GARCH(1,1) model we need to model epsilon when we use that the parameters for the distribution
# is drawn from a t-distribution we set x in dt( x, v) equal to: (vData-dMu)/sqrt(vSigma2)

LLK <- function(vPar, vData){
    vPar <- FromTilde(vPar)
    
    dAlpha <- vPar[1]
    dBeta <- vPar[2]
    dV <- vPar[3]
    dMu <- vPar[4]
    iT <- length(vData)
    
    vSigma2 <- rep(var(vData), iT)
    LL <- rep(NA, iT)
    for (i in 2:iT){
        vSigma2[i] <- dAlpha*vData[i-1]^2 + dBeta*vSigma2[i-1]
    }
    LL <- dt((vData-dMu)/sqrt(vSigma2), df = dV, log = TRUE) 
    return(-mean(LL))
}
